/*
Sample Project - Database for an eCommerce platform
Database - MySQL

Creating views on top of tables for better data security and encapsulation

*/
/* 
View for Main Category table T_MAINCATEGORY - V_MAINCATEGORY
*/
CREATE VIEW V_MAINCATEGORY
AS
SELECT  MAIN_CAT_NO,
	MAIN_CAT_NAME,
	MAIN_CAT_DESCRIPTION,
	MAIN_CAT_STATUS,
	MAIN_CAT_CREATED,
	MAIN_CAT_UPDATED
	
	FROM T_MAINCATEGORY;
	
/* 
View for Sub Category table T_SUBCATEGORY - V_SUBCATEGORY
*/

CREATE VIEW V_SUBCATEGORY
AS
SELECT  SUB_CAT_NO,
	SUB_CAT_NAME,
	SUB_CAT_DESCRIPTION,
	MAIN_CAT_NO,
	SUB_CAT_STATUS,
	SUB_CAT_CREATED,
	SUB_CAT_UPDATED
	
	FROM T_SUBCATEGORY;
	
/*
View for Products table T_PRODUCTS - V_PRODUCTS
*/


CREATE VIEW V_PRODUCTS 
AS
SELECT  PRODUCT_NO,
	PRODUCT_NAME,
	SUB_CAT_NO,
	PRODUCT_DESCRIPTION,
	PRODUCT_STATUS,
	PRODUCT_CREATED,
	PRODUCT_UPDATED
	
	FROM T_PRODUCTS;
	
/*
View for Suppliers table T_SUPPLIERS - V_SUPPLIERS
*/
	
CREATE VIEW V_SUPPLIERS
AS
SELECT  SUPPLIER_NO,
	SUPPLIER_NAME,
	SUPPLIER_ADDRESS,
	SUPPLIER_TYPE,
	SUPPLIER_CITY,
	SUPPLIER_STATUS,
	SUPPLIER_CREATED,
	SUPPLIER_UPDATED
	
	FROM T_SUPPLIERS;
	
/*
View for Product Supplier table T_PRODUCT_SUPPLIER - V_PRODUCT_SUPPLIER
*/
	
CREATE VIEW V_PRODUCT_SUPPLIER
AS
SELECT  RELATION_NO,
	PRODUCT_NO,
	SUPPLIER_NO,
	RELATION_STATUS,
	PRODUCT_PRICE,
	DELIVERY_CHARGE,
	RELATION_CREATED,
	RELATION_UPDATED
	
	FROM T_PRODUCT_SUPPLIER;
	
/*
View for Customers table T_CUSTOMERS - V_CUSTOMERS
*/
	
CREATE VIEW V_CUSTOMERS 
AS
SELECT  CUSTOMER_ID,
	CUSTOMER_NAME,
	CUSTOMER_EMAIL,
	CUSTOMER_CONTACT,
	CUSTOMER_STATUS,
	CUSTOMER_CREATED,
	CUSTOMER_UPDATED
	
	FROM T_CUSTOMERS;
	
/*
View for Customer Payment table T_CUSTOMER_PAYMENT - V_CUSTOMER_PAYMENT
*/
CREATE VIEW V_CUSTOMER_PAYMENT
AS
SELECT  PAYMENT_ID,
	CUSTOMER_ID,
	PAYMENT_TYPE,
	PAYMENT_REFERENCE,
	PAYMENT_STATUS,
	PAYMENT_CREATED,
	PAYMENT_UPDATED
	
	FROM T_CUSTOMER_PAYMENT;
	
/*
View for Customer Address table T_CUSTOMER_ADDRESS - V_CUSTOMER_ADDRESS
*/
	
CREATE VIEW V_CUSTOMER_ADDRESS
AS
SELECT  ADDRESS_ID,
	CUSTOMER_ID,
	ADDRESS_LINE1,
	ADDRESS_LINE2,
	CITY,
	PIN_CODE,
	STATE_NAME,
	CUSTOMER_CONTACT,
	ADDRESS_CREATED,
	ADDRESS_UPDATED
	
	FROM T_CUSTOMER_ADDRESS;
	
/*
View for Transaction details table T_TRANSACTION_DETAILS - V_TRANSACTION_DETAILS
*/
	
CREATE VIEW V_TRANSACTION_DETAILS
AS
SELECT  TRANSACTION_ID,
	CUSTOMER_ID,
	PAYMENT_ID,
	TRANSACTION_STATUS,
	TRANSACTION_DONE_ON
	
	FROM T_TRANSACTION_DETAILS;
	
	
/*
View for orders table T_ORDERS - V_ORDERS
*/
CREATE VIEW V_ORDERS
AS
SELECT  ORDER_ID,
	CUSTOMER_ID,
	ADDRESS_ID,
	ORDER_PLACED,
	EXPECTED_DELIVERY,
	TRANSACTION_ID
	
	FROM T_ORDERS;
/*
View to see the products tagged to an order - V_ORDER_PRODUCTS
*/	
	
CREATE VIEW V_ORDER_PRODUCTS
AS
SELECT  ORDER_RELATION_NO,
	ORDER_ID,
	PRODUCT_NO,
	SUPPLIER_ID,
	EXPECTED_DELIVERY
	
	FROM T_ORDER_PRODUCTS;	
	
	
/