/*
Project - Database for an eCommerce platform
Creating triggers for TABLES

Triggers are actions performed automatically after every DML operation (Insert, Update and Delete)

Whenever data is manipulated in the table, corresponding trigger gets executed

Insert trigger - Whenever an insert is performed on a table, this trigger gets executed
In this script, _created and _updated columns will be updated with SYSDATE while INSERT

Update trigger - Whenever an update is performed on a row, this trigger gets invoked
In this script, _updated column will be set to SYSDATE while UPDATE

*/

/*
Insert trigger for Main category table - TR_INS_MAINCATEGORY
*/
CREATE TRIGGER TR_INS_MAINCATEGORY   
AFTER INSERT ON T_MAINCATEGORY FOR EACH ROW  
BEGIN  
MAIN_CAT_CREATED = SYSDATE; 
MAIN_CAT_UPDATED = SYSDATE;
END;
/*
Update trigger for Main category table - TR_UPD_MAINCATEGORY
*/
CREATE TRIGGER TR_UPD_MAINCATEGORY   
AFTER UPDATE ON T_MAINCATEGORY FOR EACH ROW  
BEGIN  
MAIN_CAT_UPDATED = SYSDATE;
END;
/*
Insert trigger for Sub category table - TR_INS_SUBCATEGORY
*/
CREATE TRIGGER TR_INS_SUBCATEGORY   
AFTER INSERT ON T_SUBCATEGORY FOR EACH ROW  
BEGIN  
SUB_CAT_CREATED = SYSDATE; 
SUB_CAT_UPDATED = SYSDATE;
END;
/*
Update trigger for Sub category table - TR_UPD_SUBCATEGORY
*/
CREATE TRIGGER TR_UPD_SUBCATEGORY   
AFTER UPDATE ON T_SUBCATEGORY FOR EACH ROW  
BEGIN  
SUB_CAT_UPDATED = SYSDATE;
END;
/*
Insert trigger for Products table  - TR_INS_PRODUCTS
*/
CREATE TRIGGER TR_INS_PRODUCTS   
AFTER INSERT ON T_PRODUCTS FOR EACH ROW  
BEGIN  
PRODUCT_CREATED = SYSDATE; 
PRODUCT_UPDATED = SYSDATE;
END;
/*
Update trigger for Products table  - TR_UPD_PRODUCTS
*/
CREATE TRIGGER TR_UPD_PRODUCTS  
AFTER UPDATE ON T_PRODUCTS FOR EACH ROW  
BEGIN  
PRODUCT_UPDATED = SYSDATE;
END;
/*
Insert trigger for Suppliers table  - TR_INS_SUPPLIERS
*/
CREATE TRIGGER TR_INS_SUPPLIERS   
AFTER INSERT ON T_SUPPLIERS FOR EACH ROW  
BEGIN  
SUPPLIER_CREATED = SYSDATE; 
SUPPLIER_UPDATED = SYSDATE;
END;
/*
Update trigger for Suppliers table  - TR_UPD_SUPPLIERS
*/
CREATE TRIGGER TR_UPD_SUPPLIERS 
AFTER UPDATE ON T_SUPPLIERS FOR EACH ROW  
BEGIN  
SUPPLIER_UPDATED = SYSDATE;
END;
/*
Insert trigger for Customers table  - TR_INS_CUSTOMERS
*/
CREATE TRIGGER TR_INS_CUSTOMERS   
AFTER INSERT ON T_CUSTOMERS FOR EACH ROW  
BEGIN  
CUSTOMER_CREATED = SYSDATE; 
CUSTOMER_UPDATED = SYSDATE;
END;
/*
Update trigger for Customers table  - TR_UPD_CUSTOMERS
*/
CREATE TRIGGER TR_UPD_CUSTOMERS 
AFTER UPDATE ON T_CUSTOMERS FOR EACH ROW  
BEGIN  
CUSTOMER_UPDATED = SYSDATE;
END;
/*
Insert trigger for Customer Payment Methods table  - TR_INS_CUSTOMER_PAYMENT
*/
CREATE TRIGGER TR_INS_CUSTOMER_PAYMENT   
AFTER INSERT ON T_CUSTOMER_PAYMENT FOR EACH ROW  
BEGIN  
PAYMENT_CREATED = SYSDATE; 
PAYMENT_UPDATED = SYSDATE;
END;
/*
Update trigger for Customer Payment Methods table  - TR_UPD_CUSTOMER_PAYMENT
*/
CREATE TRIGGER TR_UPD_CUSTOMER_PAYMENT 
AFTER UPDATE ON T_CUSTOMER_PAYMENT FOR EACH ROW  
BEGIN  
PAYMENT_UPDATED = SYSDATE;
END;
/*
Insert trigger for Customer Address table  - TR_INS_CUSTOMER_ADDRESS
*/
CREATE TRIGGER TR_INS_CUSTOMER_ADDRESS  
AFTER INSERT ON T_CUSTOMER_ADDRESS FOR EACH ROW  
BEGIN  
ADDRESS_CREATED = SYSDATE; 
ADDRESS_UPDATED = SYSDATE;
END;
/*
Update trigger for Customer Address table  - TR_UPD_CUSTOMER_ADDRESS
*/
CREATE TRIGGER TR_UPD_CUSTOMER_ADDRESS
AFTER UPDATE ON T_CUSTOMER_ADDRESS FOR EACH ROW  
BEGIN  
ADDRESS_UPDATED = SYSDATE;
END;
/*
Insert trigger for Transactions table  - TR_INS_TRANSACTION_DETAILS
*/
CREATE TRIGGER TR_INS_TRANSACTION_DETAILS  
AFTER INSERT ON T_TRANSACTION_DETAILS FOR EACH ROW  
BEGIN  
TRANSACTION_DONE_ON = SYSDATE; 
END;
/*
Insert trigger for Orders table  - TR_INS_ORDERS
*/
CREATE TRIGGER TR_INS_ORDERS
AFTER INSERT ON T_ORDERS FOR EACH ROW  
BEGIN  
ORDER_PLACED = SYSDATE; 
END;
/