/*
Project - Database for an eCommerce platform
Filetype - Initial Data load

This file contains anonymous block to insert subcategories under Main Categories
Products will be tagged under each sub Category
*/

DECLARE
v_maincategory T_MAINCATEGORY.MAIN_CAT_NO%TYPE;
BEGIN
SELECT MAIN_CAT_NO INTO V_MAINCATEGORY WHERE UPPER(MAIN_CAT_NAME) = UPPER('fashion');
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Clothing',V_MAINCATEGORY,'Men and Women Clothing',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Footwear',V_MAINCATEGORY,'Fashion sandals, Casual shoes, formal shoes and many more',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Wallet',V_MAINCATEGORY,'Sling bags, handbags, clutches,totes',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Sportswear',V_MAINCATEGORY,'Sports tees, sports accessories, sports shoes, ',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Luggage',V_MAINCATEGORY,'Trolleys, duffle bags',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Jewellery',V_MAINCATEGORY,'Accessories for men and women',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Eyewear',V_MAINCATEGORY,'Prescription and sun glasses for men and women',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Watches',V_MAINCATEGORY,'Rose toned, Gold toned, Premium watches',TRUE);
COMMIT;
SELECT MAIN_CAT_NO INTO V_MAINCATEGORY WHERE UPPER(MAIN_CAT_NAME) = UPPER('Books');
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Fiction books','Romance, Poetry, Anthologies',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('children books','Nursery books',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Textbooks','All school and college text books',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Indian Language Books','fiction and non fiction books in all major Indian languages',TRUE);
INSERT INTO T_SUBCATEGORY (SUB_CAT_NAME,MAIN_CAT_NO,SUB_CAT_DESCRIPTION,SUB_CAT_STATUS) VALUES('Exam Central','Books for competitive exams',TRUE);
COMMIT;
END;
/