INSERT INTO T_MAINCATEGORY (MAIN_CAT_NAME,MAIN_CAT_DESCRIPTION,MAIN_CAT_STATUS) VALUES ('Fashion','Men and Women dresses',TRUE);
INSERT INTO T_MAINCATEGORY (MAIN_CAT_NAME,MAIN_CAT_DESCRIPTION,MAIN_CAT_STATUS) VALUES ('Books','Interesting reads',TRUE);
INSERT INTO T_MAINCATEGORY (MAIN_CAT_NAME,MAIN_CAT_DESCRIPTION,MAIN_CAT_STATUS) VALUES ('Electronics','Mobiles, computers, laptops, etc',TRUE);
INSERT INTO T_MAINCATEGORY (MAIN_CAT_NAME,MAIN_CAT_DESCRIPTION,MAIN_CAT_STATUS) VALUES ('Entertainment','Music, Movies, video Games',TRUE);
INSERT INTO T_MAINCATEGORY (MAIN_CAT_NAME,MAIN_CAT_DESCRIPTION,MAIN_CAT_STATUS) VALUES ('Children','Baby Products',TRUE);
COMMIT;
/