CREATE OR REPLACE PACKAGE BODY P_GETITEMS
AS
PROCEDURE P_GETPRODUCTS (V_SUBCAT T_SUBCATEGORY.SUB_CAT_NO%TYPE);
BEGIN
PROCEDURE P_GETPRODUCTS (V_SUBCAT T_SUBCATEGORY.SUB_CAT_NO%TYPE)
IS
V_SQL VARCHAR(255 CHAR);
BEGIN
V_SQL := 'SELECT  PRODUCT_NO,
	PRODUCT_NAME,
	SUB_CAT_NO,
	PRODUCT_DESCRIPTION,
	PRODUCT_STATUS,
	PRODUCT_CREATED,
	PRODUCT_UPDATED
	FROM V_PRODUCTS WHERE SUB_CAT_NO = :SUBCAT';
   EXECUTE IMMEDIATE V_SQL USING V_SUBCAT;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
END;

PROCEDURE P_STRINGSEARCH (V_STRING VARCHAR2)
IS
V_SQL VARCHAR2(255 CHAR);
BEGIN
V_SQL := 'SELECT  PRODUCT_NO,
	PRODUCT_NAME,
	SUB_CAT_NO,
	PRODUCT_DESCRIPTION,
	PRODUCT_STATUS,
	PRODUCT_CREATED,
	PRODUCT_UPDATED
	FROM V_PRODUCTS WHERE UPPER(PRODUCT_NAME) LIKE UPPER(''''%:V_STR%'''')';
   EXECUTE IMMEDIATE V_SQL USING V_STRING;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
END;


END;
/